version: "3.1" # optimal since v1.27.0, # Three mysql image services through Docker, using Docker Compose
services: 
  registration-db:
    container_name: registration-db
    fimage: mysql:latest
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=registration
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports: 
      - "3308:3308"
    volumes:
       - .:/code
       - logvolume01:/var/log

    links:
     - redis
  redis: 
    image: redis
volumes:
  logvolume01: {}